// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnfE-ZMU5Vmb-OmyWMjHRrik-c4wYFg08',
    appId: '1:252812712934:web:0fe7696bb16107042a9427',
    messagingSenderId: '252812712934',
    projectId: 'petto-app-b73df',
    authDomain: 'petto-app-b73df.firebaseapp.com',
    storageBucket: 'petto-app-b73df.appspot.com',
    measurementId: 'G-H2GGFRZ4PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBhT-EBrRtqkdu466PnLlo6evOfW2cn4',
    appId: '1:252812712934:android:c91d0e9f5edd50202a9427',
    messagingSenderId: '252812712934',
    projectId: 'petto-app-b73df',
    storageBucket: 'petto-app-b73df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1xFJigWRxD-vDuYE0hrZ29h61gtHSes',
    appId: '1:252812712934:ios:9b89b804e8c8162d2a9427',
    messagingSenderId: '252812712934',
    projectId: 'petto-app-b73df',
    storageBucket: 'petto-app-b73df.appspot.com',
    iosClientId: '252812712934-9v88rojllksvutefi7ncjpu0etd42c6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.petoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1xFJigWRxD-vDuYE0hrZ29h61gtHSes',
    appId: '1:252812712934:ios:8397b0ec10ca5f752a9427',
    messagingSenderId: '252812712934',
    projectId: 'petto-app-b73df',
    storageBucket: 'petto-app-b73df.appspot.com',
    iosClientId: '252812712934-b5olvmesm626r113ldbd4grmndtlheb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.petoApp.RunnerTests',
  );
}
